### ISSUE TITLE
DAPLink & Bootloader: Small display driver for nRF52 (COMP003)

### ISSUE THREAD

**Issue by jaustin** [microbit-foundation/standalone-error-program#1]
## Depends on

Third parties:
- N/A

## Description

Related: https://github.com/microbit-foundation/DAPLink-microbit/issues/33

One of the features we want to add to DAPLink is to scroll error codes in the micro:bit display. This will be useful for errors like trying to flash a v1 hex file into a v2. This is tricky because the KL27 where DAPLink runs doesn't have access to the display, so needs to 'ask' the nRF to do it for us.

Errors should be in the form:
Sad face-->E-->error number
https://support.microbit.org/support/solutions/articles/19000016969-micro-bit-error-codes

Therefore we need a small CODAL-less display driver for the nRF52 so that DAPLink can flash errors and the code can then drive the display. 

Existing panic code
https://github.com/lancaster-university/microbit-dal/blob/master/source/core/MicroBitDevice.cpp#L172

(may have own display stuff in there?)

This will be *bundled* in the DAPLink builds/binary as a standalone hex that DAPLink can flash in times of emergency so it needs to be small.

Goal for size is under 10kB, but we really want it to be 5kB.
Benchmark to say this achievable: the blinky for the Nordic SDK without softdevice is 6kb in hex format.
[radio_test copy.zip](https://github.com/microbit-foundation/v2/files/4718355/radio_test.copy.zip)

This could be loaded in the nRF52 to memory, like the flash algo (although this option is likely discarded), or into the nRF52 flash (better option for error permanence). This program needs to read a number of message from somewhere (from a different location in  Flash?) to scroll in the display.

Things we have at our disposal
* Nordic sample code/blinky
* Nordic radio test sent to use (attached)
* Bluetooth bootloader

We'd like the same code to be useful in the bluetooth bootloader for displaying progress and errors. This should probably be a library that the bootloader can use and a nordic sdk sample that uses that library to build a tiny program that can display errors.

For now, the code should display on, non-configurable error, E70. Once we have this working we can decide the error 'passing' mechanism with Gerardo

The code should live in this repository
https://github.com/microbit-foundation/standalone-error-program
And ideally will use the same SDK repo that Sam has created for the DAL

If the program could run out of flash or RAM (not just flash) it would allow us to use it in cases where we haven't already erased the nRF52 (say, someone drops an image onto the DAPlink drive, or another error that shouldn't erase the whole nRF52.

This COULD build on the Nordic SDK or it could just write the registers natively - the goal is small first, so if the SDK is roping in size without bringing much upside, we can ditch it.

See also https://github.com/matthewelse/microbit-bootloader/commit/5b31e6beed370a53f7f7726f9c854545c4988b1c for a tiny display driver!

## Todo

- [ ] Prototype MVP
- [ ] Measure memory consumption in KL27
- [ ] Trim down to reduce resources?

## Tracking

This task will likely be assigned to Martin.

- [ ] @jaustin to create repo for Martin
- [ ] @jaustin to sync with Martin and assign

## Testing Required

- [ ] Gerardo to test blob in DAPLink

## Reviewer

- [ ] @microbit-carlos ?

## Completion Criteria

- [ ] All items in the todo list
- [ ] ????
- [ ] Demo at sprint closure

## Conclusion

WIP.

**Comment by martinwork** [comment]
PR https://github.com/microbit-foundation/standalone-error-program/pull/12
